        version: '3'
        services:
          web:
            image: 698subhashchandra/flask-api:latest
            ports:
              - "5000:5000"
            volumes:
              - .:/app
            working_dir: /app

