version: '3.8'
services:
  web:
    build: 698subhashchandra/flask-api:latest
    context: /var/lib/jenkins/workspace/flask-app-cicd/698subhashchandra/flask-api
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    working_dir: /app
