version: '3'
services:
  web:
<<<<<<< HEAD
    build: .
=======
    build: 698subhashchandra/flaskapp:latest .
>>>>>>> bc256b5 (update compose file)
    ports:
      - "5000:5000"
    volumes:
      - .:/app
