version: '3.9'
services:
  web:
    build:
      context: .
    image: 698subhashchandra/flask-api:latest
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    working_dir: /app

